# Generated by Django 4.2.2 on 2023-06-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='country',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='operator',
            field=models.TextField(max_length=100),
        ),
    ]
