# Generated by Django 4.2.2 on 2023-06-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_phonenumber_country_alter_phonenumber_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='suka',
            field=models.TextField(default='sobaka', max_length=10),
        ),
    ]
