# Generated by Django 4.2.2 on 2023-06-11 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_sms_suka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='suka',
        ),
    ]
