# Generated by Django 4.2.2 on 2023-06-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_remove_sms_suka'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='sended',
            field=models.BooleanField(default=False),
        ),
    ]
