# Generated by Django 4.2.2 on 2023-06-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_sms_sended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name_plural': 'Номера телефонов'},
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name_plural': 'Смс'},
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='vk',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='country',
            field=models.TextField(max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='operator',
            field=models.TextField(max_length=100, verbose_name='Мобильный оператор'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone',
            field=models.BigIntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='phone',
            field=models.BigIntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='phone_from',
            field=models.TextField(verbose_name='Номер отправителя'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='sended',
            field=models.BooleanField(default=False, verbose_name='Принято'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='text',
            field=models.TextField(verbose_name='Текст смс'),
        ),
    ]
