# Generated by Django 4.2.2 on 2023-06-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_alter_phonenumber_options_alter_sms_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='vk',
        ),
    ]
