# Generated by Django 4.2.2 on 2023-06-17 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0008_phonenumber_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('finished', models.BooleanField(default=False)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.phonenumber')),
            ],
            options={
                'verbose_name_plural': 'Активации',
                'db_table': 'activation',
            },
        ),
    ]
