# Generated by Django 4.2.2 on 2023-06-19 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Активация закончена'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.phonenumber', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='service',
            field=models.CharField(max_length=100, verbose_name='Сервис'),
        ),
    ]
