# Generated by Django 4.2.2 on 2023-06-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_activation_paid_alter_activation_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доход'),
        ),
    ]
