# Generated by Django 4.2.2 on 2023-06-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_protocolkey_activation_protocol_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='protocol_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms.protocolkey'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='protocol_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms.protocolkey'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='protocol_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sms.protocolkey'),
        ),
    ]
