# Generated by Django 4.2.2 on 2023-06-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_alter_activation_protocol_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation',
            name='protocol_key',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='protocol_key',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='protocol_key',
        ),
        migrations.DeleteModel(
            name='ProtocolKey',
        ),
    ]
