# Generated by Django 4.2.2 on 2023-06-19 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0015_remove_activation_protocol_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='phone',
        ),
        migrations.AddField(
            model_name='sms',
            name='phone_number',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sms.phonenumber', verbose_name='Номер телефона'),
        ),
    ]
